Style/Documentation:
  Exclude:
    - 'app/**/*'
    - 'db/**/*'
    - 'rubopcop/*/*'
    - 'config/**/*'
Metrics/LineLength:
  Exclude:
    - 'config/**/*'
    - 'Gemfile'

AllCops:
  Exclude:
    - 'test/**/*'
    - 'bin/**/*'
    - 'db/schema.rb'

Naming/FileName:
  Exclude:
    - 'spec/views/**/*'
